// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfvEW6HBsHnMuIYeR06Q3T1XVfJzQcpPI',
    appId: '1:310700366975:web:32d863bac94a6edb9cf34a',
    messagingSenderId: '310700366975',
    projectId: 'elmatgr-ec97a',
    authDomain: 'elmatgr-ec97a.firebaseapp.com',
    storageBucket: 'elmatgr-ec97a.appspot.com',
    measurementId: 'G-LLT1J8G72K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIIrl81K-yvDQUHQoGvn2YRmpKWFdoxLA',
    appId: '1:310700366975:android:0993e393ff40cc199cf34a',
    messagingSenderId: '310700366975',
    projectId: 'elmatgr-ec97a',
    storageBucket: 'elmatgr-ec97a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY4t4ZdZ5j0AJ0udsuCldXm9q3_MzaAe4',
    appId: '1:310700366975:ios:b8539bc92ca748339cf34a',
    messagingSenderId: '310700366975',
    projectId: 'elmatgr-ec97a',
    storageBucket: 'elmatgr-ec97a.appspot.com',
    iosBundleId: 'com.example.elmatgr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY4t4ZdZ5j0AJ0udsuCldXm9q3_MzaAe4',
    appId: '1:310700366975:ios:cb747b586f6f5ee69cf34a',
    messagingSenderId: '310700366975',
    projectId: 'elmatgr-ec97a',
    storageBucket: 'elmatgr-ec97a.appspot.com',
    iosBundleId: 'com.example.elmatgr.RunnerTests',
  );
}
